version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: isagro_api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - isagro-net

  postgres:
    image: postgis/postgis:14-3.4
    container_name: isagro_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - isagro-net

volumes:
  pgdata:

networks:
  isagro-net:
    driver: bridge
